accounts/urls.py
from django.urls import path
from .views import (Register, Login, Logout, RegisterMember)

app_name='accounts'
urlpatterns = [
    path('register/', Register.as_view(), name='register'),
    path('register_member/', RegisterMember.as_view(), name='register_member'),
    path('login/', Login.as_view(), name='login'),
    path('logout/', Logout.as_view(), name='logout'),
]

apps/urls.py
from django.urls import path
from .views import (Section)


app_name='apps'
urlpatterns = [
    path('section/', Section.as_view(), name='section'),
]

ducku/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('apps.urls')),
    path('', include('home.urls')),
    path('', include('posts.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import (Index, AboutUs, Home)

app_name='home'
urlpatterns = [
    path('', Index.as_view(), name='index'),
    path('about/', AboutUs.as_view(), name='about'),
    path('home/', Home.as_view(), name='home'),
]

posts/urls.py
from django.urls import path
from .views import (PostCreateView, PostDetailView, 
                    PostListView, PostUpdateView, 
                    UserPostListView, PostDeleteView)

app_name = 'post'
urlpatterns = [
    path('create_post/', PostCreateView.as_view(), name='post-create'),
    path("post/<slug:slug>/detail/", PostDetailView.as_view(), name="post-detail"),
    path("post/<slug:slug>/update/", PostUpdateView.as_view(), name="post-update"),
    path("post/<slug:slug>/delete/", PostDeleteView.as_view(), name="post-delete"),
    path("list_post/", PostListView.as_view(), name="post-list"),
    path("user_list_post/", UserPostListView.as_view(), name="user-post-list"),
]

templates/includes/is_admin_home.html
<h1>HOME PAGE - admin home</h1>
<main>
    
</main>

templates/includes/is_superuser_home.html
<h1>HOME PAGE - superuser home</h1>
<main>
    
</main>

templates/includes/is_user_home.html
<h1>HOME PAGE - user home</h1>
<main>
    
</main>

templates/includes/nav.html
<nav>
    <a href="{% url 'home:index' %}">Home</a>
    <a href="{% url 'home:about' %}">About</a>
    
    {% if user.is_admin and not user.is_superuser %}
    | <a href="{% url 'accounts:register_member' %}">Register Member</a> |
    | <a href="{% url 'apps:section' %}">Add Section</a> |
    {% endif %}

    {% if user.is_user and not user.is_superuser %}
    | <a href="{% url 'post:post-create' %}">Create Article</a> |
    | <a href="{% url 'post:user-post-list' %}">My Articles</a> |
    | <a href="{% url 'post:post-list' %}">All Article Visible to me</a> |
    {% endif %}
    
    {% if not user.is_authenticated %}
    <a href=" {% url 'accounts:register' %}">Register</a>
    <a href="{% url 'accounts:login' %}">Login</a>
    {% else %}
    <a href="{% url 'accounts:logout' %}">Logout</a> ||
    {{ user.username }}
    {% endif %}
    
</nav>